### ISSUE TITLE
Add `car_passenger` as mode in plans.xml

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/matsim-drt#11]
I need to specify `car_passenger` in the population (plans.xml) input. If the mode of car_passengers is specified as car, then there will be too many cars on the network

There is no need to model people travelling together. Eqasim handles car_passengers differently. 

### TODO

- [x] Add car_passenger as mode in acbm output
- [x] update config
     - [x] qsim::mainMode: keep this as "car"
     - [x] routing::networkModes: change from "car" to "car, car_passenger"

**Comment by Hussein-Mahfouz** [comment]
Updated here: https://github.com/Urban-Analytics-Technology-Platform/acbm/pull/73/commits/e7b317a1c7bab0281cc9afbcb4bb8a5dca333c74

**Comment by Hussein-Mahfouz** [comment]
Does isCarPassenger need to be added as a person attribute as well? If so, what is the correct way to do it? Ref: https://github.com/eqasim-org/eqasim-java/blob/7ed1950498ca0f6b73a4540e40de6037af4a682b/core/src/test/java/org/eqasim/TestSimulationPipeline.java#L497-L512

**Comment by Hussein-Mahfouz** [comment]
Yes, I need both:
- `car_passenger` as a mode
- `isPassenger `as a person attribute
