### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Hussein-Mahfouz/matsim-drt#15]
## Supply Input

- [x] merge gtfs feeds
- [ ] add networkVehicles properly #12 

#### personAttributes
- [x] add car_passenger as mode in acbm #11 
- [x] eqasim requires an "age" parameter. In the plans.xml, it is "age_years". 
    - [x] Change to "age" #13 
    - [x] Remove temporary fix in [21b783d](https://github.com/Hussein-Mahfouz/matsim-drt/commit/21b783df64c2e2edb0d5e675249704f8ea261bb6)
- [x] update to include all variables needed in #16 
    - [x] isPassenger
    - [x] hasPTsubscription
    - [x] isStudent
    - [x] sex
    - [x] hhIncome
    
#### activityAttributes
- [ ] isUrban

## Configuration

- [ ] Refactor code so that I can run scenarios directly from RunDMCSimulation, without the need to run other scripts first

## Discrete Choice Model
- [x] Implement steps in #16 
- [ ] check consistency with Leeds mode choice model: #20

## Add DRT
- [x] #24 

## Calibration
- [ ] https://github.com/Hussein-Mahfouz/matsim-drt/issues/32
